routes:
  default:    'default:welcome:both'
  home:       'default:home:connected'
  register:   'user:register:disconnected'
  login:      'user:login:disconnected'
  logout:     'user:logout:connected'
  upload:     'file:upload:connected'
  download:   'file:download:connected'
  rename:     'file:rename:connected'
  replace:    'file:replace:connected'
  remove:     'file:remove:connected'
  addFolder:  'file:addFolder:connected'
  move:       'file:move:connected'
  show:       'file:show:connected'
  write:      'file:write:connected'
  open:       'nav:open:connected'
  to_parent:  'nav:toParent:connected'
defaultAction: 'default'